YARN=yarn
BABEL=./node_modules/.bin/babel
WEBPACK=./node_modules/.bin/webpack
SQLITIS=sqlitis

JSX_DIR=static/scripts/jsx/
JS_DIR=static/scripts/js/

install:
	yarn

dev-server:
	$(SQLITIS) --web --debug

dev-webpack-watch:
	$(WEBPACK) -w --mode development
